_extends: .github
repository:
  name: remark-preset-lint
  description: remark preset to configure remark-lint with markdown style conventions
  homepage: 'https://npm.im/@dsmjs/remark-preset-lint'
  private: false
  topics: hacktoberfest
